/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyItem"
      | "getListing"
      | "getListingByIndex"
      | "listItem"
      | "listingCount"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Listed" | "Purchased"): EventFragment;

  encodeFunctionData(
    functionFragment: "buyItem",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListing",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getListingByIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listItem",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listingCount",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "buyItem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getListing", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getListingByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listItem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listingCount",
    data: BytesLike
  ): Result;
}

export namespace ListedEvent {
  export type InputTuple = [
    seller: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish,
    priceWei: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    nftContract: string,
    tokenId: bigint,
    priceWei: bigint
  ];
  export interface OutputObject {
    seller: string;
    nftContract: string;
    tokenId: bigint;
    priceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    nftContract: AddressLike,
    tokenId: BigNumberish,
    priceWei: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    nftContract: string,
    tokenId: bigint,
    priceWei: bigint
  ];
  export interface OutputObject {
    buyer: string;
    nftContract: string;
    tokenId: bigint;
    priceWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Marketplace extends BaseContract {
  connect(runner?: ContractRunner | null): Marketplace;
  waitForDeployment(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyItem: TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;

  getListing: TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [
      [string, bigint, boolean] & {
        seller: string;
        priceWei: bigint;
        sold: boolean;
      }
    ],
    "view"
  >;

  getListingByIndex: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, string, bigint, boolean] & {
        nftContract: string;
        tokenId: bigint;
        seller: string;
        priceWei: bigint;
        sold: boolean;
      }
    ],
    "view"
  >;

  listItem: TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish, priceWei: BigNumberish],
    [void],
    "nonpayable"
  >;

  listingCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyItem"
  ): TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getListing"
  ): TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish],
    [
      [string, bigint, boolean] & {
        seller: string;
        priceWei: bigint;
        sold: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getListingByIndex"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, bigint, string, bigint, boolean] & {
        nftContract: string;
        tokenId: bigint;
        seller: string;
        priceWei: bigint;
        sold: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "listItem"
  ): TypedContractMethod<
    [nftContract: AddressLike, tokenId: BigNumberish, priceWei: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listingCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Listed"
  ): TypedContractEvent<
    ListedEvent.InputTuple,
    ListedEvent.OutputTuple,
    ListedEvent.OutputObject
  >;
  getEvent(
    key: "Purchased"
  ): TypedContractEvent<
    PurchasedEvent.InputTuple,
    PurchasedEvent.OutputTuple,
    PurchasedEvent.OutputObject
  >;

  filters: {
    "Listed(address,address,uint256,uint256)": TypedContractEvent<
      ListedEvent.InputTuple,
      ListedEvent.OutputTuple,
      ListedEvent.OutputObject
    >;
    Listed: TypedContractEvent<
      ListedEvent.InputTuple,
      ListedEvent.OutputTuple,
      ListedEvent.OutputObject
    >;

    "Purchased(address,address,uint256,uint256)": TypedContractEvent<
      PurchasedEvent.InputTuple,
      PurchasedEvent.OutputTuple,
      PurchasedEvent.OutputObject
    >;
    Purchased: TypedContractEvent<
      PurchasedEvent.InputTuple,
      PurchasedEvent.OutputTuple,
      PurchasedEvent.OutputObject
    >;
  };
}
